### ISSUE TITLE
Enable Bubbling for CommandEvent

### ISSUE THREAD

**Issue by davidmerrique** [keithamus/invokers-polyfill#45]
I'd like to create a `--toggle-modal` command.

Currently, CommandEvent doesn't bubble, requiring individual listeners for each dialog. 
Enabling bubbling would allow for a single, global listener.

```javascript
document.addEventListener('command', (event) => {
  if (event.command === '--toggle-modal' && event.target.localName === 'dialog') {
    event.target.open ? event.target.close() : event.target.showModal();
  }
});
```

**Comment by keithamus** [comment]
Command events do not bubble because their element should handle them, they're not a UI event that requires such traversal. This is per spec.

You can use the capturing event phase to do what you're after. For example:

```diff
 document.addEventListener('command', (event) => {
   if (event.command === '--toggle-modal' && event.target.localName === 'dialog') {
     event.target.open ? event.target.close() : event.target.showModal();
   }
-});
+}, true);
```

I'll close this as I think the solution provided will solve your issue, and there's nothing we can action in the polyfill as we do not want to change the semantics of bubbling between the polyfill and the browser behaviour.
